name: plant_disease_detector
description: "AI-powered crop disease identification app for Sri Lankan farmers."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Routing
  go_router: ^18.0.1

  # State Management
  flutter_riverpod: ^2.5.1

  # Backend
  supabase_flutter: ^2.5.0

  # Persistence
  shared_preferences: ^2.2.3

  # Camera & Image Handling
  image_picker: ^1.1.2
  image_cropper: ^12.2.1

  # Network
  connectivity_plus: ^6.0.3

  # Animations
  lottie: ^3.3.1

  # UI Components
  percent_indicator: ^4.2.4

  # Fonts
  google_fonts: ^6.2.1

  # Localization
  intl: ^0.20.2
  fl_chart: ^1.2.0
  geolocator: ^14.0.3
  geocoding: ^5.0.0
  http: ^1.6.0
  flutter_dotenv: ^6.0.1
  flutter_map: ^8.3.2
  latlong2: ^0.10.1
  camera: ^0.12.1
  drift: ^2.24.0
  sqlite3_flutter_libs: ^0.6.0+eol
  path_provider: ^2.1.6
  tflite_flutter: ^0.12.1
  firebase_core: ^4.15.0
  firebase_crashlytics: ^5.4.0
  riverpod_annotation: ^2.6.1
  image: ^4.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  drift_dev: ^2.24.0
  riverpod_generator: ^2.6.5
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/models/
